"""DICTIONARY OF MOS CODES AND DESCRIPTIONS"""
global CODES
CODES = {
    '09L': 'Interpreter/Translator',
    '11B': 'Infrantryman',
    '11C': 'Indirect Fire Infantryman',
    '11Z': 'Infantry Senior Sergeant',
    '12B': 'Combat Engineer',
    '12C': 'Bridge Crewmember',
    '12D': 'Diver',
    '12G': 'Quarrying Specialist',
    '12H': 'Construction Engineering Supervisor',
    '12K': 'Plumber',
    '12M': 'Firefighter',
    '12N': 'Horizontal Construction Engineer',
    '12P': 'Prime Power Production Specialist',
    '12Q': 'Power Line Distribution Specialist',
    '12R': 'Interior Electrician',
    '12T': 'Technical Engineer',
    '12V': 'Concrete and Asphalt Equipment Operator',
    '12W': 'Carpentry and Masonry Specialist',
    '12X': 'General Engineering Supervisor',
    '12Y': 'Geospatial Engineer',
    '12Z': 'Combat Engineering Senior Sergeant',
    '13D': 'Cannon Crewmember',
    '13F': 'Fire Support Specialist',
    '13M': 'Multiple Launch Rocket System (MLRS)/High Mobility Artillery Rocket System (HIMARS) Crewmember',
    '13P': 'Operational Fire Direction Specialist',
    '13R': 'Field Artillery Firefinder Radar Operator',
    '13T': 'Field Artillery Surveyor/Meteorological Crewmember',
    '13Z': 'Field Artillery Senior Sergeant',
    '14E': 'Patriot Fire Control Enhanced Operator',
    '14G': 'Air Defense Battle Management System Operator',
    '14H': 'Air Defense Enhanced Early Warning System Operator',
    '14J': 'Air Defense C41 Tactical Operations Center Enhanced Operator-Maintainer',
    '14S': 'Air and Missle Defense Crewmember',
    '14T': 'Patriot Launching Station Enhanced Operator-Maintainer',
    '14Z': 'Air Defense Artillery Senior Sergeant',

    '91A': 'Abrams Tank System Maintainer',
    '91B': 'Wheel Vehicle Mechanic',
    '91C': 'Utilities Equipment Repairer',
    '91D': 'Power-Generation Equipment Repairer',
    '91E': 'Allied Trades Specialist',
    '91F': 'Small Arms/Artillery Repairer',
    '91G': 'Fire Control Repairer',
    '91H': 'Track Vehicle Repairer',
    '91J': 'Quartermaster and Chemical Equipment Repairer',
    '91K': 'Armament Repairer',
    '91L': 'Construction Equipment Repairer',
    '91M': 'Bradley Fighting Vehicle System Maintainer',
    '91P': 'Artillery Mechanic',
    '91S': 'Stryker Systems Maintainer',
    '91X': 'Maintenance Supervisor',
    '91Z': 'Mechanical Maintenance Supervisor',
    '92A': 'Automated Logistical Specialist',
    '92F': 'Petroleum Supply Specialist',
    '92G': 'Food Service Specialist',
    '92L': 'Petroleum Laboratory Specialist',
    '92M': 'Mortuary Affairs Specialist',
    '92R': 'Parachute Rigger',
    '92S': 'Shower/Laundry and Clothing Repair Specialist',
    '92W': 'Water Treatment Specialist',
    '92Y': 'Unit Supply Specialist',
    '92Z': 'Senior Noncommissioned Logistician'
}